In [1]:
import pandas as pd

In [2]:
df2 = pd.read_csv('data/SRI-R-HRC.csv')

In [3]:
df2 = df2[df2['CEI_Score_2017'] == 100]
df2.head()

,Exchange,Symbol,Name,LastSale,MarketCap,IPOyear,Sector,industry,Summary Quote,Financials,...,2a_Spousal_Benefits,2b_Parity_Spousal_Benefits,2c_Trans_Inclusive_Healthcare,3a_Org Competency,3b_ERG,4_Positive_LGBTQ_Engagmt,Negative_LGBTQ_Demerit,CEI_Score_2017,CEI_Score_2016,Fortune_1000_Rank
0,NYSE,MMM,3M Company,217.72,$129.93B,NaN,Health Care,Medical/Dental Instruments,http://www.nasdaq.com/symbol/mmm,1,...,F,F,F,F,F,F,NaN,100,100.0,98.0
2,NasDaq,SIRI,Sirius XM Holdings Inc.,5.71,$26.34B,NaN,Consumer Services,Broadcasting,http://www.nasdaq.com/symbol/siri,1,...,F,F,F,F,F,F,NaN,100,100.0,NaN
6,NYSE,LUV,Southwest Airlines Company,59.12,$35.39B,NaN,Transportation,Air Freight/Delivery Services,http://www.nasdaq.com/symbol/luv,1,...,F,F,F,F,F,F,NaN,100,100.0,161.0
9,NYSE,S,Sprint Corporation,7.12,$28.46B,2013.0,Public Utilities,Telecommunications Equipment,http://www.nasdaq.com/symbol/s,1,...,F,F,F,F,F,F,NaN,100,100.0,NaN
10,NasDaq,SBUX,Starbucks Corporation,55.72,$80.45B,1992.0,Consumer Services,Restaurants,http://www.nasdaq.com/symbol/sbux,1,...,F,F,F,F,F,F,NaN,100,100.0,187.0

In [4]:
df2['new_mkt'] = df2.MarketCap.apply(lambda x: float(x[1:-1]))
df2.head()

,Exchange,Symbol,Name,LastSale,MarketCap,IPOyear,Sector,industry,Summary Quote,Financials,...,2b_Parity_Spousal_Benefits,2c_Trans_Inclusive_Healthcare,3a_Org Competency,3b_ERG,4_Positive_LGBTQ_Engagmt,Negative_LGBTQ_Demerit,CEI_Score_2017,CEI_Score_2016,Fortune_1000_Rank,new_mkt
0,NYSE,MMM,3M Company,217.72,$129.93B,NaN,Health Care,Medical/Dental Instruments,http://www.nasdaq.com/symbol/mmm,1,...,F,F,F,F,F,NaN,100,100.0,98.0,129.93
2,NasDaq,SIRI,Sirius XM Holdings Inc.,5.71,$26.34B,NaN,Consumer Services,Broadcasting,http://www.nasdaq.com/symbol/siri,1,...,F,F,F,F,F,NaN,100,100.0,NaN,26.34
6,NYSE,LUV,Southwest Airlines Company,59.12,$35.39B,NaN,Transportation,Air Freight/Delivery Services,http://www.nasdaq.com/symbol/luv,1,...,F,F,F,F,F,NaN,100,100.0,161.0,35.39
9,NYSE,S,Sprint Corporation,7.12,$28.46B,2013.0,Public Utilities,Telecommunications Equipment,http://www.nasdaq.com/symbol/s,1,...,F,F,F,F,F,NaN,100,100.0,NaN,28.46
10,NasDaq,SBUX,Starbucks Corporation,55.72,$80.45B,1992.0,Consumer Services,Restaurants,http://www.nasdaq.com/symbol/sbux,1,...,F,F,F,F,F,NaN,100,100.0,187.0,80.45

In [5]:
df2 = df2[['Sector', 'Symbol', 'LastSale', 'new_mkt']]
df2.columns = ['name', 'Symbol', 'LastSale', 'new_mkt']
df2.dropna(inplace=True)
df2.head()

                 name Symbol  LastSale  new_mkt
0         Health Care    MMM    217.72   129.93
2   Consumer Services   SIRI      5.71    26.34
6      Transportation    LUV     59.12    35.39
9    Public Utilities      S      7.12    28.46
10  Consumer Services   SBUX     55.72    80.45

In [6]:
len(df2)

210

In [6]:
j = (df2.groupby(['name'], as_index=True)
        .apply(lambda x: x[['Symbol','new_mkt']].to_dict('r'))
        .reset_index()
        .rename(columns={0:'children'})
        .to_json('data/test_19NOV.json', orient='records'))